package practice;

import java.io.IOException;

public class TestingScenario {
	
	private int a =25;
	
	
	public static void main(String[] args) {
	
		
		
		try
		{
		}
		catch(ArithmeticException e)  
        {  
         System.out.println("Arithmetic Exception occurs");  
        }    
		catch(ArrayIndexOutOfBoundsException e)  
        {  
         System.out.println("ArrayIndexOutOfBounds Exception occurs");  
        }    
		
	}
}


